repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.1.0
  hooks:
  - id: reorder-python-imports
- repo: https://github.com/psf/black
  rev: "22.3.0"
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: "4.0.1"
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: end-of-file-fixer
  - id: check-json
  - id: check-yaml
    exclude: ^helm-chart/nbviewer/templates/
  - id: check-case-conflict
  - id: check-executables-have-shebangs
